{% set name = "exo_puppies" %}
{% set version = "0.4.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exo_puppies-{{ version }}.tar.gz
  sha256: 7fc4e4907fb139ad608ae8a05dbd6688bcaf03637a7efa0c25f3dd8a7f5cf4e9

build:
  entry_points:
    - pup = puppies.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - astropy >=3.1
    - matplotlib-base >=1.3.1
    - mc3 >=3.0.6
    - python
    - scipy >=1.4.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - puppies
  commands:
    - pip check
    - pup --help
  requires:
    - pip

about:
  home: https://github.com/pcubillos/puppies
  summary: The Public Photometry Pipeline for Exoplanets
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/puppies
  doc_url: https://puppies.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
